### PR TITLE
Dont convert buffers

### PR DESCRIPTION
**Pull request by technoweenie**
We discussed this the other day.  This seems like a better solution.  Though, you can use something like this to sniff out a buffer:

```
if !(body instanceof Buffer)
  body = body.toString()
res.write(body)
```

### CODE REVIEW

**Comment by jed** [comment]
yeah, i think the best bet for now is to just pass the body through. if someone needs more information about errors that happen from passing non-String/Buffer objects, they can put an app upstream.

oh, and thanks for giving me a chance to see the new awesome pull request UI! you guys are awesome.

**Comment by technoweenie** [comment]
Agreed.  I think 99% of the time you'll be passing a utf-8 string, or binary data already in a buffer from something else.  

Btw I'll be pushing up fab.static.js in a bit too.  Doing a little internal monitoring app for ryan :)

**Comment by jed** [comment]
cool... but i think i closed the issue without accepting the pull. what do i do now?

**Comment by technoweenie** [comment]
Ah, you merge the branch manually.  We'll be adding a merge button, but there's some stuff that they need to do on the backend to support it efficiently.

**Comment by technoweenie** [comment]
Gah!

```
http:443
    throw new TypeError("first argument must be a string, Array, or Buffer");
          ^
TypeError: first argument must be a string, Array, or Buffer
```

`body` was an exception:

```
{ message: 'ENOENT, No such file or directory \'./public/javascripts/smoothie.js\''
, stack: [Getter/Setter]
, errno: 2
, path: './public/javascripts/smoothie.js'
}
```

**Comment by technoweenie** [comment]
Ok, I'm just going to listen to process.uncaughtException for now, but here's one way you could catch this in fab:

```
try {
  res.write( body );
} catch(err) {
  fab.events.emit('error', err)
  // other crap
}
```

The idea is fab.events could be an emitter that sends out errors or other events...

**Comment by jed** [comment]
d'oh, i just merged. what do you mean `body` was an exception? exactly what type of object is it choking on?

**Comment by technoweenie** [comment]
Oh, it was a bug in fab.static, sending an err object from something to fab.  I just didn't like that it was a weird error.  I think we should catch that error and raise it with a pointer to the body object.  Someone can catch it in on their own and get the stack trace and all that.  Some `fab.events` thing isn't needed.

I really want fab.js to be able to report errors and keep chugging along.  I think that'll require some real usage and careful try/catch blocks that know how to close up streams and all that.

**Comment by jed** [comment]
yeah, i was thinking that just like nodejs functions have a `( err, data )` signature, we could either:

go whole hog on HTTP and pass errors like this:

```
write( "this is an error", { status: 500 } )
```

checking them like this:

```
if ( head.status >= 500 ) { ... }
```

or, attach them to the `head` object like this:

```
write( undefined, { error: new Error( "oh noes" ) } )
```

and check them like this:

```
if ( head.error ) { ... }
```

what do you think?

**Comment by technoweenie** [comment]
I kind of like `head.errors`, but `if (head.errors)` will always be true.

**Comment by jed** [comment]
`errors` as in multiple? why would it always be true? not sure i follow.

actually, it'd need to be 

```
if ( head && head.status >= 500 ) { ... }
```

or

```
if ( head && head.error ) { ... }
```

**Comment by technoweenie** [comment]
`head.errors` would be an array, which is always truthy.  So I vote for option 2 (`if(head && head.error)`).

**Comment by jed** [comment]
that's probably a good idea, since (fab) doesn't need to be limited to just HTTP.

**Pull request merged**
